### PR TITLE
fix plugin download

### PR DESCRIPTION
**Pull request by henriiik**
This PR fixes the problems mentioned in this issue: https://github.com/pulumi/pulumi/issues/9606

### CODE REVIEW

**Review by ringods — CHANGES_REQUESTED** [review]
I will review this PR later more thoroughly, but there is still a wrong path for the Go modules:

https://github.com/pulumiverse/pulumi-sentry/blob/main/provider/resources.go#L184

The Github organization should be `pulumiverse`.

**Comment by henriiik** [comment]
> I will review this PR later more thoroughly, but there is still a wrong path for the Go modules:
> 
> https://github.com/pulumiverse/pulumi-sentry/blob/main/provider/resources.go#L184
> 
> The Github organization should be `pulumiverse`.

Good catch, thanks!

**Review by 1oglop1 — APPROVED** [review]
LGTM

**Comment by henriiik** [comment]
@ringods i have made the change you requested.

**Comment by ringods** [comment]
@henriiik can we hold off on merging this one? I talked to a colleague of mine at Pulumi and he is going to perform some fixes to get Github releases downloads correctly working for all providers.

**Comment by henriiik** [comment]
@ringods alright.

**Comment by ringods** [comment]
@henriiik this should land shortly in a pulumi release:

https://github.com/pulumi/pulumi/commit/60d8462484f93ae843559c465cced463d3d2373c

**Comment by ringods** [comment]
I think this PR will be superseded by https://github.com/pulumi/pulumi/pull/9984

**Comment by henriiik** [comment]
> I think this PR will be superseded by https://github.com/pulumi/pulumi/pull/9984

@ringods that would be great! 🤞

**Comment by ringods** [comment]
@henriiik this should be fixed when using pulumi 3.53.3. Docs are here:

https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/#support-for-github-releases

I'm going to close this PR in favor of the direct support for Github urls.

**Pull request closed without merging**
