### PR TITLE
fix logo

### PR DESCRIPTION
**Pull request by susanev**

### CODE REVIEW

**Review by henriiik — APPROVED** [review]
Thanks!

**Comment by henriiik** [comment]
@susanev do we have to make a release for it to show up in the registry?

**Comment by susanev** [comment]
@henriiik yah, it requires a release

**Comment by henriiik** [comment]
@susanev release is out :)

https://github.com/pulumiverse/pulumi-sentry/releases/tag/v0.0.6

**Comment by susanev** [comment]
@henriiik looks like the url was changed back to the pulumiverse mascot in https://github.com/pulumiverse/pulumi-sentry/pull/16

**Comment by henriiik** [comment]
@susanev ah, i see. I just re-ran the build scripts since the build was failing after merging this.

**Comment by henriiik** [comment]
new PR https://github.com/pulumiverse/pulumi-sentry/pull/17

**Pull request merged**
